

KOSUL YUK A,$21
	YAZ A,<DENETIM>
	DON

OKUMA YUK A,<DURUM>
	VE A,$1
	DEE OKUMA
	YUK B,<ALICI>
	DON

YAZMA YUK A,<DURUM>
	VE A,$2
	DEE YAZMA
	YAZ B,<VERICI>
	DON

SATBA YUK B,$0D
	ALT YAZMA
	YUK B,$0A
	ALT YAZMA
	DON

