
	BAS $1000
	VER $1,$2,$3,$4,$33,$34,$36,$44,$66,$72,$AA,$40,$3F,$55,$41,$5A
	VER $1,$2,$3,$4,$33,$34,$36,$44,$66,$72,$AA,$40,$3F,$55,$41,$5A
	VER $1,$2,$3,$4,$33,$34,$36,$44,$66,$72,$AA,$40,$3F,$55,$41,$5A
	VER $1,$2,$3,$4,$33,$34,$36,$44,$66,$72,$AA,$40,$3F,$55,$41,$5A

DIZI	EÞT	$1000	
SON	EÞT	$2000

	BAS $300
START	YAZ $FF,<YÖNLEN.B>
	YUK A,$10
	YAZ A,<DURUM>		
	YUK SK,DIZI	
GERI	YUK A,<SK+00>
YOKLA	YUK B,<DURUM>
	VE B,$80
	DEE YOKLA
	KAR A,$41
	DEK ILERI
	KAR A,$5A
	DEB ILERI
	YAZ A,<ÝSKELE.B>
	SIL 4,<DURUM>
	KUR 4,<DURUM>
ILERI	ART SK
	KAR SK,SON
	DED GERI
	KES





		
	